sudo: required
dist: trusty

language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz

install:
  - sudo perl devkitARMupdate.pl
  - tar -xvf cmake-3.1.0-Linux-x86_64.tar.gz
  - export PATH="$PWD/cmake-3.1.0-Linux-x86_64/bin/:$PATH"

script:
  - git submodule update --init --recursive
  - ./build.sh

env:
  global:
    secure: "QeQ3FDs8vOcB7+TJBPIszTPo6EuYOTcqTlC15fAXTHLLnGsY36ySSMKXKq9aV5mqJr9t92WGY169fAW35vg9wwQAx09A2EIEkaqLysozkNxaR9LralgwEEAXXJP2lD5NvJ0n13PMPloGyDCnjBRUjJ+WdDz5H6F329PbItKo5uE="

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
        GITDATE="`git show -s --date=short --format='%ad' | sed 's/-//g'`"
        GITREV="`git show -s --format='%h'`"
        REV_NAME_BS="decrypt9-${GITDATE}-${GITREV}-bootstrap"
        REV_NAME_B2="decrypt9-${GITDATE}-${GITREV}-brahma2"

        sudo apt-get -qq install lftp p7zip-full
        mkdir "$REV_NAME_BS" "$REV_NAME_B2"

        cp -R README.md build/source/decrypt9-bs.bin scripts "$REV_NAME_BS"
        7z a "$REV_NAME_BS" "$REV_NAME_BS/*"
        cp -R README.md build/source/Decrypt9.3dsx build/source/Decrypt9.smdh scripts "$REV_NAME_B2"
        7z a "$REV_NAME_B2" "$REV_NAME_B2/*"

        lftp -c "open -u builds,$BUILD_PASSWORD sftp://archshift.com; put -O '/decrypt9/nightly/bootstrap' '${REV_NAME_BS}.7z'"
        lftp -c "open -u builds,$BUILD_PASSWORD sftp://archshift.com; put -O '/decrypt9/nightly/brahma2' '${REV_NAME_B2}.7z'"
    fi
